
CONFIG_QSDK_WIFI_SCRIPT_GIT_REPOSITORY="qsdk-wifi-script.git"
CONFIG_QSDK_WIFI_SCRIPT_GIT_URL=""
CONFIG_QSDK_WIFI_SCRIPT_GIT_TREEISH="qsdk-wifi-script-dni131"

CONFIG_WLAN_COMMON_GIT_TREEISH="fb2534be5dc42f14d33fb2d52e1eaa1a769454ed"
CONFIG_WLAN_COMMON_GIT_REPOSITORY="wlan-common.git"
CONFIG_WLAN_COMMON_GIT_URL=""
